services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=blog_password'
      - 'POSTGRES_USER=blog_user'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-net

  blog:
    container_name: blog
    image: 'lucasferraz95/blog:1.0.0'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://blog-postgres-1:5432/blog'
    ports:
      - "8080:8080"
    networks:
      - blog-net
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  blog-net:
    external: true
