services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=blog_password'
      - 'POSTGRES_USER=blog_user'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
