CREATE TABLE POSTS (
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    BODY TEXT NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);